=== PROSLab/BPMN-Inspector/src/main/resources/static/schema/references.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="references" type="tReferences"/>
	<xs:complexType name="tReferences">
		<xs:sequence>
			<xs:element ref="element" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="element" type="tElement"/>
	<xs:complexType name="tElement">
		<xs:sequence>
			<!-- name of the parent element if needed for hierarchie -->
			<xs:element name="parent" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<!-- names of the child elements -->
			<xs:element name="child" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
			<!-- all references, which can be found for this element -->
			<xs:element ref="reference" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
		<!-- name of the element -->
		<xs:attribute name="name" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:element name="reference" type="tReference"/>
	<xs:complexType name="tReference">
		<xs:sequence>
			<!-- name of the reference -->
			<xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<!-- all possible (super-) types by their names (uses the hierarchie of the elements) -->
			<xs:element name="type" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<!-- The number used in the bachelor thesis -->
		<xs:attribute name="number" type="xs:int" use="required"/>
		<!-- QName: true, IDREF: false -->
		<xs:attribute name="qname" type="xs:boolean" use="required"/>
		<!-- Attribute: true, Element: false -->
		<xs:attribute name="attribute" type="xs:boolean" use="required"/>
	</xs:complexType>
</xs:schema>

=== PROSLab/BPMN-Inspector/src/main/resources/static/schema/references.xml
<?xml version="1.0" encoding="UTF-8"?>
<references xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="references.xsd">
	<element name="association">
		<reference number="4" qname="true" attribute="true">
			<name>sourceRef</name>
		</reference>
		<reference number="5" qname="true" attribute="true">
			<name>targetRef</name>
		</reference>
	</element>
	<element name="group">
		<reference number="6" qname="true" attribute="true">
			<name>categoryValueRef</name>
			<type>categoryValue</type>
		</reference>
	</element>
	<element name="correlationKey">
		<reference number="7" qname="true" attribute="false">
			<name>correlationPropertyRef</name>
			<type>correlationProperty</type>
		</reference>
	</element>
	<element name="correlationPropertyRetrievalExpression">
		<reference number="8" qname="true" attribute="true">
			<name>messageRef</name>
			<type>message</type>
		</reference>
	</element>
	<element name="correlationSubscription">
		<reference number="9" qname="true" attribute="true">
			<name>correlationKeyRef</name>
			<type>correlationKey</type>
		</reference>
	</element>
	<element name="correlationPropertyBinding">
		<reference number="10" qname="true" attribute="true">
			<name>correlationPropertyRef</name>
			<type>correlationProperty</type>
		</reference>
	</element>
	<element name="error">
		<reference number="11" qname="true" attribute="true">
			<name>structureRef</name>
			<type>itemDefinition</type>
		</reference>
	</element>
	<element name="escalation">
		<reference number="12" qname="true" attribute="true">
			<name>structureRef</name>
			<type>itemDefinition</type>
		</reference>
	</element>
	<element name="formalExpression">
		<reference number="13" qname="true" attribute="true">
			<name>evaluatesToTypeRef</name>
			<type>itemDefinition</type>
		</reference>
	</element>
	<element name="flowElement">
		<child>flowNode</child>
		<child>sequenceFlow</child>
		<child>dataObject</child>
		<child>dataObjectReference</child>
		<child>dataStoreReference</child>
		<reference number="14" qname="true" attribute="false">
			<name>categoryValueRef</name>
			<type>categoryValue</type>
		</reference>
	</element>
	<element name="message">
		<reference number="16" qname="true" attribute="true">
			<name>itemRef</name>
			<type>itemDefinition</type>
		</reference>
	</element>
	<element name="resourceParameter">
		<reference number="17" qname="true" attribute="true">
			<name>type</name>
			<type>itemDefinition</type>
		</reference>
	</element>
	<element name="sequenceFlow">
		<parent>flowElement</parent>
		<reference number="18" qname="false" attribute="true">
			<name>sourceRef</name>
			<type>activity</type>
			<type>gateway</type>
			<type>exclusiveGateway</type>
			<type>inclusiveGateway</type>
			<type>parallelGateway</type>
			<type>complexGateway</type>
			<type>eventBasedGateway</type>
			<type>event</type>
			<type>throwEvent</type>
			<type>catchEvent</type>
		</reference>
		<reference number="19" qname="false" attribute="true">
			<name>targetRef</name>
			<type>activity</type>
			<type>gateway</type>
			<type>exclusiveGateway</type>
			<type>inclusiveGateway</type>
			<type>parallelGateway</type>
			<type>complexGateway</type>
			<type>eventBasedGateway</type>
			<type>event</type>
			<type>throwEvent</type>
			<type>catchEvent</type>
		</reference>
	</element>
	<element name="flowNode">
		<parent>flowElement</parent>
		<child>gateway</child>
		<child>exclusiveGateway</child>
		<child>inclusiveGateway</child>
		<child>parallelGateway</child>
		<child>complexGateway</child>
		<child>eventBasedGateway</child>
		<child>activity</child>
		<child>choreographyActivity</child>
		<child>choreographyTask</child>
		<child>subChoreography</child>
		<child>callChoreography</child>
		<child>event</child>
		<child>throwEvent</child>
		<child>catchEvent</child>
		<reference number="20" qname="true" attribute="false">
			<name>incoming</name>
			<type>sequenceFlow</type>
		</reference>
		<reference number="21" qname="true" attribute="false">
			<name>outgoing</name>
			<type>sequenceFlow</type>
		</reference>
	</element>
	<element name="operation">
		<reference number="23" qname="true" attribute="false">
			<name>inMessageRef</name>
			<type>message</type>
		</reference>
		<reference number="24" qname="true" attribute="false">
			<name>outMessageRef</name>
			<type>message</type>
		</reference>
		<reference number="25" qname="true" attribute="false">
			<name>errorRef</name>
			<type>error</type>
		</reference>
	</element>
	<element name="collaboration">
		<child>choreography</child>
		<child>globalChoreographyTask</child>
		<child>globalConversation</child>
		<reference number="27" qname="true" attribute="false">
			<name>choreographyRef</name>
			<type>choreography</type>
		</reference>
	</element>
	<element name="participant">
		<reference number="28" qname="true" attribute="true">
			<name>processRef</name>
			<type>process</type>
		</reference>
		<reference number="29" qname="true" attribute="false">
			<name>interfaceRef</name>
			<type>interface</type>
		</reference>
		<reference number="30" qname="true" attribute="false">
			<name>endPointRef</name>
			<type>endPoint</type>
		</reference>
	</element>
	<element name="partnerEntity">
		<reference number="31" qname="true" attribute="false">
			<name>participantRef</name>
			<type>participant</type>
		</reference>
	</element>
	<element name="partnerRole">
		<reference number="32" qname="true" attribute="false">
			<name>participantRef</name>
			<type>participant</type>
		</reference>
	</element>
	<element name="participantAssociation">
		<reference number="33" qname="true" attribute="false">
			<name>innerParticipantRef</name>
			<type>participant</type>
		</reference>
		<reference number="34" qname="true" attribute="false">
			<name>outerParticipantRef</name>
			<type>participant</type>
		</reference>
	</element>
	<element name="messageFlow">
		<reference number="35" qname="true" attribute="true">
			<name>sourceRef</name>
			<type>pool</type>
			<type>participant</type>
			<type>activity</type>
			<type>event</type>
			<type>throwEvent</type>
			<type>catchEvent</type>
		</reference>
		<reference number="36" qname="true" attribute="true">
			<name>targetRef</name>
			<type>pool</type>
			<type>participant</type>
			<type>activity</type>
			<type>event</type>
			<type>throwEvent</type>
			<type>catchEvent</type>
		</reference>
		<reference number="37" qname="true" attribute="true">
			<name>messageRef</name>
			<type>message</type>
		</reference>
	</element>
	<element name="process">
		<parent>callableElement</parent>
		<reference number="47" qname="true" attribute="false">
			<name>supports</name>
			<type>process</type>
		</reference>
		<reference number="48" qname="true" attribute="true">
			<name>definitionalCollaborationRef</name>
			<type>collaboration</type>
		</reference>
	</element>
	<element name="activity">
		<parent>flowNode</parent>
		<child>task</child>
		<child>serviceTask</child>
		<child>sendTask</child>
		<child>receiveTask</child>
		<child>userTask</child>
		<child>manualTask</child>
		<child>scriptTask</child>
		<child>businessRuleTask</child>
		<child>subProcess</child>
		<child>adHocSubProcess</child>
		<child>transaction</child>
		<child>callActivity</child>
		<reference number="49" qname="false" attribute="true">
			<name>default</name>
			<type>sequenceFlow</type>
		</reference>
	</element>
	<element name="resourceRole">
		<reference number="50" qname="true" attribute="false">
			<name>resourceRef</name>
			<type>resource</type>
		</reference>
	</element>
	<element name="resourceParameterBinding">
		<reference number="51" qname="true" attribute="true">
			<name>parameterRef</name>
			<type>resourceParameter</type>
		</reference>
	</element>
	<element name="serviceTask">
		<parent>activity</parent>
		<reference number="52" qname="true" attribute="true">
			<name>operationRef</name>
			<type>operation</type>
		</reference>
	</element>
	<element name="sendTask">
		<parent>activity</parent>
		<reference number="53" qname="true" attribute="true">
			<name>messageRef</name>
			<type>message</type>
		</reference>
		<reference number="54" qname="true" attribute="true">
			<name>operationRef</name>
			<type>operation</type>
		</reference>
	</element>
	<element name="receiveTask">
		<parent>activity</parent>
		<reference number="55" qname="true" attribute="true">
			<name>messageRef</name>
			<type>message</type>
		</reference>
		<reference number="56" qname="true" attribute="true">
			<name>operationRef</name>
			<type>operation</type>
		</reference>
	</element>
	<element name="callActivity">
		<parent>activity</parent>
		<reference number="57" qname="true" attribute="true">
			<name>calledElement</name>
			<type>process</type>
			<type>globalTask</type>
			<type>globalUserTask</type>
			<type>globalManualTask</type>
			<type>globalScriptTask</type>
			<type>globalBusinessRuleTask</type>
		</reference>
	</element>
	<element name="callableElement">
		<child>process</child>
		<child>globalTask</child>
		<child>globalUserTask</child>
		<child>globalManualTask</child>
		<child>globalScriptTask</child>
		<child>globalBusinessRuleTask</child>
		<reference number="58" qname="true" attribute="false">
			<name>supportedInterfaceRefs</name>
			<type>interface</type>
		</reference>
	</element>
	<element name="ioBinding">
		<reference number="59" qname="false" attribute="true">
			<name>inputDataRef</name>
			<type>dataInput</type>
		</reference>
		<reference number="60" qname="false" attribute="true">
			<name>outputDataRef</name>
			<type>dataOutput</type>
		</reference>
		<reference number="61" qname="true" attribute="true">
			<name>operationRef</name>
			<type>operation</type>
		</reference>
	</element>
	<element name="multiInstanceLoopCharacteristics">
		<reference number="62" qname="true" attribute="false">
			<name>loopDataInputRef</name>
			<type>property</type>
			<type>dataObject</type>
